#pragma once

#define BUTTON_WHITE 2
#define BUTTON_BLACK 6
#define BUTTON_SELECT 5

#define WHITE_LED_GREEN 3
#define WHITE_LED_RED 4
#define BLACK_LED_GREEN 8
#define BLACK_LED_RED 7

#define BUZZER 10

#define LED_ON LOW
#define LED_OFF HIGH

#define LCD_ADDRESS 0x27
#define LCD_COLUMNS 16
#define LCD_ROWS 2

#define EEPROM_TIMER_MODE 0
#define EEPROM_PLAYTIME_MINUTES 1
#define EEPROM_INCREMENT_SECONDS 2
